// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFOeA7mG1BXpP7z8IYnezsAttUMBy3WJA',
    appId: '1:1050339169135:web:9dee43962f53d627f80e9a',
    messagingSenderId: '1050339169135',
    projectId: 'stefanini-8a79c',
    authDomain: 'stefanini-8a79c.firebaseapp.com',
    storageBucket: 'stefanini-8a79c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOuz2yxYf1cJIrR6OlFMwGHCbQs97Jk7s',
    appId: '1:1050339169135:android:db8bdf2321358e6df80e9a',
    messagingSenderId: '1050339169135',
    projectId: 'stefanini-8a79c',
    storageBucket: 'stefanini-8a79c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-AhozHLaGqTtjO40kujNLy4zzgxN--w',
    appId: '1:1050339169135:ios:401c6da9e038bad7f80e9a',
    messagingSenderId: '1050339169135',
    projectId: 'stefanini-8a79c',
    storageBucket: 'stefanini-8a79c.appspot.com',
    iosBundleId: 'com.example.flutterCleanArchitecture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy-AhozHLaGqTtjO40kujNLy4zzgxN--w',
    appId: '1:1050339169135:ios:b05528bb0311a813f80e9a',
    messagingSenderId: '1050339169135',
    projectId: 'stefanini-8a79c',
    storageBucket: 'stefanini-8a79c.appspot.com',
    iosBundleId: 'com.example.flutterCleanArchitecture.RunnerTests',
  );
}
